// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vfinance_api.DataManager;

namespace vfinance_api.Migrations
{
    [DbContext(typeof(vFinDbContext))]
    [Migration("20210612110641_payments")]
    partial class payments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("vfinance_api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("UserCode")
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id")
                        .HasName("PK_AppUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("Idx_Email");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("Idx_AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("vfinance_api.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("FilePath")
                        .HasColumnType("varchar(95)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_AttachmentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("FileName")
                        .IsUnique()
                        .HasDatabaseName("Idx_FileName");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("Idx_FilePath");

                    b.HasIndex("LoanId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("vfinance_api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessMobile1")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessMobile2")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessName")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile1")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile2")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("vfinance_api.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_ExpenseId");

                    b.HasIndex("Amount")
                        .IsUnique()
                        .HasDatabaseName("Idx_Amount");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasDatabaseName("Idx_Category");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("vfinance_api.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("LoanTerm")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PaymentStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ReferredBYId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPaidAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id")
                        .HasName("PK_LoanId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanNumber")
                        .IsUnique()
                        .HasDatabaseName("Idx_LoanNumber");

                    b.HasIndex("ReferredBYId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("vfinance_api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CollectedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("LoadIdId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentDueNumber")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_PaymentId");

                    b.HasIndex("LoadIdId");

                    b.HasIndex("PaymentDueNumber")
                        .IsUnique()
                        .HasDatabaseName("Idx_PaymentDueNumber");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("vfinance_api.Models.Attachment", b =>
                {
                    b.HasOne("vfinance_api.Models.Customer", null)
                        .WithMany("Attachments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("vfinance_api.Models.Expense", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ExpenseId");

                    b.HasOne("vfinance_api.Models.Loan", null)
                        .WithMany("Attachments")
                        .HasForeignKey("LoanId");
                });

            modelBuilder.Entity("vfinance_api.Models.Loan", b =>
                {
                    b.HasOne("vfinance_api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("vfinance_api.Models.Customer", "ReferredBY")
                        .WithMany()
                        .HasForeignKey("ReferredBYId");

                    b.Navigation("Customer");

                    b.Navigation("ReferredBY");
                });

            modelBuilder.Entity("vfinance_api.Models.Payment", b =>
                {
                    b.HasOne("vfinance_api.Models.Loan", "LoadId")
                        .WithMany()
                        .HasForeignKey("LoadIdId");

                    b.Navigation("LoadId");
                });

            modelBuilder.Entity("vfinance_api.Models.Customer", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("vfinance_api.Models.Expense", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("vfinance_api.Models.Loan", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
